### ISSUE TITLE
NodeJS 25 is out

### ISSUE THREAD

**Issue by cesco69** [uNetworking/uWebSockets.js#1194]
Hi! Really appreciate your time on this project. By the way, Node.js 25 just dropped — any plans to support it?

https://nodejs.org/en/blog/release/v25.0.0

**Comment by uNetworkingAB** [comment]
> uws_darwin_arm64_141.node
	uws_darwin_x64_141.node

It compiles on macOS but Linux is having issues with this header: https://v8.github.io/api/head/v8-source-location_8h_source.html

std::source_location::current() is not available on Linux?

**Comment by uNetworkingAB** [comment]
Wtf

```
In file included from targets/node-v25.0.0/include/node/v8-array-buffer.h:14:
targets/node-v25.0.0/include/node/v8-object.h:957:37: error: expected expression
        I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                    ^
targets/node-v25.0.0/include/node/v8-object.h:980:37: error: expected expression
        I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                    ^
In file included from src/addon.cpp:26:
In file included from targets/node-v25.0.0/include/node/v8.h:26:
targets/node-v25.0.0/include/node/v8-context.h:481:35: error: expected expression
      I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                  ^
targets/node-v25.0.0/include/node/v8-context.h:501:35: error: expected expression
      I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                  ^
```

**Comment by Dimous** [comment]
Hello! What about uws_win32_x64_141.node? I see https://github.com/uNetworking/uWebSockets.js/actions/runs/18607954203/job/53060965189#logs succeed but there is no artifact.

**Comment by uNetworkingAB** [comment]
`D:\a\uWebSockets.js\uWebSockets.js\uWebSockets.js\uWebSockets\uSockets\lsquic\src\lshpack\lshpack.c(1546,36): error C2220: the following warning is treated as an error [D:\a\uWebSockets.js\uWebSockets.js\uWebSockets.js\uWebSockets\uSockets\lsquic\src\liblsquic\lsquic.vcxproj]
D:\a\uWebSockets.js\uWebSockets.js\uWebSockets.js\uWebSockets\uSockets\lsquic\src\lshpack\lshpack.c(1546,36): warning C5286: implicit conversion from enum type 'lsxpack_flag' to enum type '<unnamed-enum-DTEF_NAME_HASH>'; use an explicit cast to silence this warning [D:\a\uWebSockets.js\uWebSockets.js\uWebSockets.js\uWebSockets\uSockets\lsquic\src\liblsquic\lsquic.vcxproj]
      D:\a\uWebSockets.js\uWebSockets.js\uWebSockets.js\uWebSockets\uSockets\lsquic\src\lshpack\lshpack.c(1546,36):
      to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings`

**Comment by uNetworkingAB** [comment]
Macos and linux have binaries now

**Comment by Dimous** [comment]
Hello again! uws_win32_x64_141.node now exists but its empty.

https://github.com/uNetworking/uWebSockets.js/blob/binaries/uws_win32_x64_141.node

**Comment by aleksraiden** [comment]
We have segfault at app start if build in docker node:25.0-alpine3.22 :(

**Comment by uNetworkingAB** [comment]
It works on Ubuntu

```
Welcome to Node.js v25.0.0.
Type ".help" for more information.
> require("uWebSockets.js")
{
  App: [Function (anonymous)],
  SSLApp: [Function (anonymous)],
  H3App: [Function (anonymous)],
  getString: [Function (anonymous)],
  setString: [Function (anonymous)],
  getInteger: [Function (anonymous)],
  setInteger: [Function (anonymous)],
  incInteger: [Function (anonymous)],
  lock: [Function (anonymous)],
  unlock: [Function (anonymous)],
  getIntegerKeys: [Function (anonymous)],
  getStringKeys: [Function (anonymous)],
  deleteString: [Function (anonymous)],
  deleteInteger: [Function (anonymous)],
  deleteStringCollection: [Function (anonymous)],
  deleteIntegerCollection: [Function (anonymous)],
  setTimeout: [Function (anonymous)],
  clearTimeout: [Function (anonymous)],
  arm: [Function (anonymous)],
  _cfg: [Function (anonymous)],
  getParts: [Function (anonymous)],
  us_listen_socket_close: [Function (anonymous)],
  us_socket_local_port: [Function (anonymous)],
  DISABLED: 0,
  SHARED_COMPRESSOR: 1,
  SHARED_DECOMPRESSOR: 256,
  DEDICATED_DECOMPRESSOR: 3840,
  DEDICATED_COMPRESSOR: 248,
  DEDICATED_COMPRESSOR_3KB: 145,
  DEDICATED_COMPRESSOR_4KB: 146,
  DEDICATED_COMPRESSOR_8KB: 163,
  DEDICATED_COMPRESSOR_16KB: 180,
  DEDICATED_COMPRESSOR_32KB: 197,
  DEDICATED_COMPRESSOR_64KB: 214,
  DEDICATED_COMPRESSOR_128KB: 231,
  DEDICATED_COMPRESSOR_256KB: 248,
  DEDICATED_DECOMPRESSOR_32KB: 3840,
  DEDICATED_DECOMPRESSOR_16KB: 3584,
  DEDICATED_DECOMPRESSOR_8KB: 3328,
  DEDICATED_DECOMPRESSOR_4KB: 3072,
  DEDICATED_DECOMPRESSOR_2KB: 2816,
  DEDICATED_DECOMPRESSOR_1KB: 2560,
  DEDICATED_DECOMPRESSOR_512B: 2304,
  LIBUS_LISTEN_EXCLUSIVE_PORT: 1,
  DeclarativeResponse: [class DeclarativeResponse]
}
```

**Comment by uNetworkingAB** [comment]
Windows has a binary now

**Comment by uasan** [comment]
Doesn't work on MacOS 26.0.1 (Apple M1 Pro)
Exists file: uWebSockets.js/uws_darwin_arm64_141.node

> node -v
v25.0.0

> Error: This version of uWS.js (v20.53.0) supports only Node.js versions 20, 22, 24 and 25 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
Error: Module did not self-register: '...uWebSockets.js/uws_darwin_arm64_141.node'.

**Comment by aleksraiden** [comment]
Node.js v24.0.1 - latest uWS needs a glibc 2.38 ? Debian bookworm, ldd (Debian GLIBC 2.36-9+deb12u13) 2.36  

`Error:` This version of uWS.js (v20.53.0) supports only Node.js versions 20, 22, 24 and 25 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /opt/raiden/lastvalue/uws/uws_linux_x64_137.node)`

**Comment by uNetworkingAB** [comment]
> Doesn't work on MacOS 26.0.1 (Apple M1 Pro) Exists file: uWebSockets.js/uws_darwin_arm64_141.node
> 
> > node -v
> > v25.0.0
> 
> > Error: This version of uWS.js (v20.53.0) supports only Node.js versions 20, 22, 24 and 25 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
> > Error: Module did not self-register: '...uWebSockets.js/uws_darwin_arm64_141.node'.

Oh that's right the macOS Node.js 25 build fails the same way the Linux one used to:

```
In file included from targets/node-v25.0.0/include/node/v8-array-buffer.h:14:
targets/node-v25.0.0/include/node/v8-object.h:957:37: error: expected expression
        I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                    ^
targets/node-v25.0.0/include/node/v8-object.h:980:37: error: expected expression
        I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                    ^
In file included from src/addon.cpp:26:
In file included from targets/node-v25.0.0/include/node/v8.h:26:
targets/node-v25.0.0/include/node/v8-context.h:481:35: error: expected expression
      I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                  ^
targets/node-v25.0.0/include/node/v8-context.h:501:35: error: expected expression
      I::ReadExternalPointerField<{internal::kFirstEmbedderDataTag,
                                  ^
```

**Comment by uNetworkingAB** [comment]
I need to raise macOS version to 15. This Node.js version uses very recent C++20 features

**Comment by uNetworkingAB** [comment]
> Node.js v24.0.1 - latest uWS needs a glibc 2.38 ? Debian bookworm, ldd (Debian GLIBC 2.36-9+deb12u13) 2.36
> 
> `Error:` This version of uWS.js (v20.53.0) supports only Node.js versions 20, 22, 24 and 25 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
> 
> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /opt/raiden/lastvalue/uws/uws_linux_x64_137.node)`

Yes. Ubuntu 24.04 is requirement. Glibc 2.39

**Comment by uNetworkingAB** [comment]
@uasan test latest binary just now

**Comment by uasan** [comment]
> @uasan test latest binary just now

Installations from the `binaries` branch, works, thanks
