### ISSUE TITLE
how to get it to work with ubuntu WSL2.0

### ISSUE THREAD

**Issue by jcherrabi** [uNetworking/uWebSockets.js#659]
Hello everyone,
anyone knows how do i get the library to work under ubuntu20.04 WSL2.0.. i get the following error:
`                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^
Error: This version of µWS is not compatible with your Node.js build:
Error: Cannot find module './uws_linux_x64_93.node'`

Using nvm with node v16.12.0 and i tried earlier version with no success.

i appreciate any help..
thanks.

**Comment by alexhultman** [comment]
That error message needs to be improved.

You are running an old version of Uws.js

**Comment by jcherrabi** [comment]
i swicthed to yarn and i still get the same error: i ran 
`yarn add uWebSockets.js@uNetworking/uWebSockets.js#v20.5.0`

**Comment by jcherrabi** [comment]
Thanks.
well i found the issue:
yarn worked but when i try to run it on port 80 it requires node to run with sudo and when i add sudo node it doesn't work and gives the above error..
so the question is how do i run the websocket and listen to port 80?

**Comment by alexhultman** [comment]
You can Google that on your own.

**Comment by jcherrabi** [comment]
thanks i did already figured out how to run node on port 80 thanks to google as you said and i was sharing the above comment just so you can use it to improve the error message that's all..

thanks for your help :)
cheers,
